'use server';

/**
 * @fileOverview An AI tool to analyze technician performance.
 * - analyzeTechnicianPerformance - A function that handles the performance analysis.
 * - TechnicianPerformanceInput - The input type for the function.
 * - TechnicianPerformanceOutput - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const TechnicianPerformanceInputSchema = z.object({
  technicians: z.array(z.object({
    id: z.string(),
    name: z.string(),
    payoutPerHour: z.number(),
    totalRevenue: z.number(),
    totalHoursWorked: z.number(),
  })).describe('A list of technicians with their revenue and work hours.')
});
export type TechnicianPerformanceInput = z.infer<typeof TechnicianPerformanceInputSchema>;

const TechnicianPerformanceOutputSchema = z.array(
    z.object({
        technicianId: z.string(),
        name: z.string(),
        totalRevenue: z.number().describe('The total revenue generated by the technician.'),
        totalPayout: z.number().describe('The total amount paid out to the technician (hours worked * payout per hour).'),
        summary: z.string().describe('A brief, insightful one-sentence summary of the technician\'s performance comparing their revenue to their payout. Highlight their profitability.'),
    })
);
export type TechnicianPerformanceOutput = z.infer<typeof TechnicianPerformanceOutputSchema>;

export async function analyzeTechnicianPerformance(input: TechnicianPerformanceInput): Promise<TechnicianPerformanceOutput> {
    return analyzeTechnicianPerformanceFlow(input);
}

const prompt = ai.definePrompt({
    name: 'analyzeTechnicianPerformancePrompt',
    input: { schema: TechnicianPerformanceInputSchema },
    output: { schema: TechnicianPerformanceOutputSchema },
    prompt: `You are an expert business analyst for a salon. Your task is to analyze the financial performance of technicians.

For each technician, you will be given their total revenue, total hours worked, and payout per hour.

You must calculate the 'totalPayout' for each technician using the formula:
totalPayout = totalHoursWorked * payoutPerHour

Then, compare the 'totalRevenue' to the 'totalPayout' to assess profitability.

Based on this analysis, provide a concise, one-sentence summary of each technician's performance. For example, "Generates high revenue relative to their payout, making them a top performer" or "Their payout is high compared to the revenue they generate, suggesting an area for improvement."

Technician Data:
{{#each technicians}}
- Name: {{name}}
  - Payout Per Hour: {{payoutPerHour}}
  - Total Revenue: {{totalRevenue}}
  - Total Hours Worked: {{totalHoursWorked}}
{{/each}}

Return a JSON array with the technicianId, name, totalRevenue, calculated totalPayout, and a summary for each.`,
});


const analyzeTechnicianPerformanceFlow = ai.defineFlow(
  {
    name: 'analyzeTechnicianPerformanceFlow',
    inputSchema: TechnicianPerformanceInputSchema,
    outputSchema: TechnicianPerformanceOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
