// This file is automatically generated. Do not modify.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
};

// Custom Auth Configuration
export interface AuthUser {
  id: string;
  email: string;
  name?: string;
  role?: string;
  token?: string;
}

// Simple in-memory auth store (replace with your auth API)
export const authConfig = {
  apiUrl: process.env.NEXT_PUBLIC_AUTH_API_URL || 'http://localhost:3000/api/auth',
  tokenKey: 'auth_token',
  userKey: 'auth_user',
};

// Auth helper functions
export const auth = {
  async login(email: string, password: string): Promise<AuthUser> {
    const response = await fetch(`${authConfig.apiUrl}/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    
    if (!response.ok) {
      throw new Error('Login failed');
    }
    
    const data = await response.json();
    if (data.token) {
      localStorage.setItem(authConfig.tokenKey, data.token);
      localStorage.setItem(authConfig.userKey, JSON.stringify(data.user));
    }
    return data.user;
  },

  async register(email: string, password: string, name?: string): Promise<AuthUser> {
    const response = await fetch(`${authConfig.apiUrl}/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password, name }),
    });

    if (!response.ok) {
      throw new Error('Registration failed');
    }

    const data = await response.json();
    if (data.token) {
      localStorage.setItem(authConfig.tokenKey, data.token);
      localStorage.setItem(authConfig.userKey, JSON.stringify(data.user));
    }
    return data.user;
  },

  async updateProfile(profile: { name?: string; photoURL?: string }): Promise<AuthUser | null> {
    const token = auth.getToken();
    if (!token) throw new Error('Not authenticated');

    const response = await fetch(`${authConfig.apiUrl}/profile`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify(profile),
    });

    if (!response.ok) {
      throw new Error('Update profile failed');
    }

    const data = await response.json();
    if (data.user) {
      localStorage.setItem(authConfig.userKey, JSON.stringify(data.user));
      return data.user;
    }
    return null;
  },

  async logout(): Promise<void> {
    localStorage.removeItem(authConfig.tokenKey);
    localStorage.removeItem(authConfig.userKey);
  },

  async getCurrentUser(): Promise<AuthUser | null> {
    const userStr = localStorage.getItem(authConfig.userKey);
    return userStr ? JSON.parse(userStr) : null;
  },

  getToken(): string | null {
    return localStorage.getItem(authConfig.tokenKey);
  },

  isAuthenticated(): boolean {
    return !!localStorage.getItem(authConfig.tokenKey);
  },
};
